---
#   Copyright 2012 Tim Ellis
#   CTO: PalominoDB
#   The Palomino Cluster Tool
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# zoo.cfg on each server must include list of all servers in the ensemble, and
# each server must also have a myid file in its data directory (by default
# /var/lib/zookeeper) that identifies it as one of the servers in the ensemble.
- hosts: ZooKeepers
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: create/chown ZooKeepers data directory
     action: file dest=/var/lib/zookeeper state=directory mode=0755 owner=zookeeper group=zookeeper

   - name: initialize the ZooKeepers
     action: shell creates=/var/lib/zookeeper/myid /etc/init.d/zookeeper-server init --myid=$myid

   - name: ensure /var/.../zookeeper is for zookeeper
     action: shell chown -R zookeeper:zookeeper /var/log/zookeeper /var/lib/zookeeper


- hosts: masters:slaves
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
   - ../variables-hbase.yml
  tasks:
   - name: Setup HBase Configuration for masters, slaves
     action: template src=../templates/$item dest=/etc/hbase/conf/$item owner=hbase mode=0644
     with_items:
      - hadoop-metrics.properties
      - hbase-env.sh
      - hbase-site.xml
      - jmxremote.access
      - jmxremote.passwd
      - log4j.properties
      - regionservers

   - name: ensure /var/lib/hdfs/.ssh (homedir of hdfs) exists
     action: file dest=/var/lib/hdfs/.ssh state=directory mode=0700 owner=hdfs group=hdfs

   # re-use the MHA pub/privkey for HBase
   - name: privkey for hdfs to SSH around at will
     action: copy src=$cluster_sudoUserPrivateKey dest=/var/lib/hdfs/.ssh/id_dsa mode=0600 owner=hdfs group=hdfs

   # re-use the MHA pub/privkey for HBase
   - name: pubkey for hdfs to SSH around at will
     action: authorized_key user=$cluster_passwordlessSudoUser key="$cluster_sudoUserPublicKey"


- hosts: NameNodes
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: ensure hdfs:///hbase exists for HBase to store its files
     action: shell creates=/var/lib/hbase/HBaseRootDirCreated sudo -u hdfs -s hadoop fs -mkdir -p /hbase && touch /var/lib/hbase/HBaseRootDirCreated

   - name: ensure hdfs:///hbase is owned by HBase user
     action: shell sudo -u hdfs -s hadoop fs -chown hbase:hbase /hbase


- hosts: ZooKeepers
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: restart ZooKeeper service
     action: service name=zookeeper-server state=restarted pattern=zookeeper


- hosts: HMasters
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: restart HMaster service
     action: service name=hbase-master state=restarted pattern=-master-


- hosts: RegionServers
  user: ubuntu
  sudo: True
  vars_files:
   - ../../currentPalominoConfiguration.yml
  tasks:
   - name: restart RegionServer services
     action: service name=hbase-regionserver state=restarted pattern=RegionServer

